config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  # devise_scope :users do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end

  resources :users,only: [:edit,:update,:index]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index,:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :members
  has_many :messages
  has_many :users, through: :members

   def show_last_message
      #メッセージが存在してるかどうか
    if (last_message = messages.last).present?
      # last_message.text? ? last_message.text : '画像が投稿されています'
      last_message != nil  ? last_message.text : '画像が投稿されています'
      # price==0
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
    belongs_to :group
    belongs_to :user
    # mount_uploader :image, ImageUploader
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    belongs_to :group

    validates :text, presence: true, unless: :image?
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :members
  has_many :messages
  has_many :groups, through: :members
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
   before_action :set_group, only: [:edit, :update]

  def index
  end

  def edit
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end



  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end


 def set_group
    @group = Group.find(params[:id])
 end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @message = @group.messages.new(message_params)

    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(params[:group_id]), notice: 'メッセージが送信されました' }
        format.json
      end
    else
      @messages = @group.messages.includes(:user)

      flash.now[:alert] = 'メッセージを入力してください. '
      render :index
    end
  end

  private
  def message_params
    params.require(:message).permit(:text, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    #currentユーザーは取り除く
    # @users =User.where('name LIKE(?) and name != ?', "%#{params[:keyword]}%",current_user.name)
    @users =User.where('name LIKE(?) and name != ?', "%#{params[:keyword]}%",current_user.name)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit

  end

  def update
    if current_user.update(user_params)
        redirect_to root_path
      else
        render :edit
      end
  end

  private
  def user_params
    params.require(:user).permit(:mail,:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      =f.label :チャットメンバーを追加, class: "chat-group-form__label"
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input{class: "chat-group-form__input", id: "user-search-field", placeholder: "追加したいユーザー名を入力してください", type: "text"}
      #user-search-result
      #chat-group-users
        .chat-group-user.clearfix#chat-group-user
          =f.hidden_field :user_ids, name: 'group[user_ids][]', value: current_user.id
          %p.chat-group-user__name
            = current_user.name
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.contents
  = render 'shared/side_bar'
  / renderの中にrenderは使ってはいけない。divの中に閉じてあげる
  .right-contents
    .right-mainbody
      = render 'shared/right-message'
  .footer-content
    = render 'shared/footer'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group }

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    = csrf_meta_tag
    %meta{charset: "utf-8"}/
    %title chatspace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_message-footer.html.haml
.form_content
  = form_for [@group, @message] do |f|
    = f.text_field :text, class: 'form__message', placeholder: 'type a message'
    .form__mask
      = f.label :image, class: 'form__mask__image' do
        = fa_icon 'picture-o', class: 'icon'
        = f.file_field :image, class: 'hidden'
    = f.submit 'Send', class: 'form__submit'

app/views/messages/_message.html.haml
.chat-box{id: "#{message.id}"}
  .nameday-box
    %p.chat-name
      = message.user.name
    %p.chat-day
      = message.created_at
  .text-box
    = message.text

app/views/messages/index.html.haml
.contents
  = render 'shared/side_bar'
  .right-contents
    = render 'shared/header'
    .right-mainbody
      = render :partial => "message", :collection => @messages, :as => "message"
  .footer-content
    = render 'message-footer'

app/views/shared/_footer.html.haml
.form_content
  / = form_tag(group_messages_path, method: :post) do
  %label.upload-label{for: "upload-icon"}
    %i.fa.fa-picture-o
      = file_field_tag :image, id: "upload-icon",style: "display:none"
  %textarea{:placeholder => "type a message",:cols => "140", :name => "text", :rows => "2",:src => "far.fa-image"}
  %input#submit{:type => "submit", :value => "Send"}/

app/views/shared/_header.html.haml
.topbox
  .editbox
    = link_to 'edit', "/groups/#{@group.id}/edit", method: :get
.main-header.clearfix
  %p.header-groupname
    = @group.name
  .menber-name
  Menber:
  = current_user.name

app/views/shared/_right-message.html.haml
.right-mainbody
  .chat-box
    .nameday-box
      %p.chat-name
      %p.chat-day
    .text-box
      %p.chat-text

app/views/shared/_side_bar.html.haml
.left-contents
  .lefttop-content
    = link_to edit_user_path(current_user) do
      %i.fa.fa-cog
    = link_to new_group_path do
      %i.fa.fa-pencil-square-o
    %p.lefttop
      = current_user.name
  .leftbottom-content
    - current_user.groups.each do |group|
      = link_to group_messages_path(group) do
        %p
          = group.name
          %br
          %span
          = group.show_last_message

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'